version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "02:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "22:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
