linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - revive
    # - tagliatelle
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G401
      - G501
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 10
  misspell:
    ignore-words:
      - thushan
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        yaml: camel
        toml: camel
        env: upperSnake

run:
  concurrency: 8
  timeout: 2m

issues:
  exclude-dirs:
    - doc
  exclude-files:
    - '_test\.go$'
  exclude-rules:
    - path: internal/util/request.go
      linters:
        - gosec
      text: "G404"
