linters:
    enable:
        - asciicheck
        - bodyclose
        - durationcheck
        - errname
        - errorlint
        - exhaustive
        - exportloopref
        - forcetypeassert
        - goimports
        - gosec
        - makezero
        - misspell
        - nakedret
        - nilerr
        - noctx
        - nolintlint
        - nosprintfhostport
        - predeclared
        - revive
        # - tagliatelle
        - unconvert
        - unparam
        - wastedassign

linters-settings:
    revive:
        rules:
            - name: unused-parameter
              disabled: true
    exhaustive:
        default-signifies-exhaustive: true
    gosec:
        excludes:
            - G401
            - G501
    misspell:
        ignore-words:
            - thushan
    tagliatelle:
        case:
          # Default: false
          use-field-name: true
          rules:
            json: camel
            yaml: camel
            toml: camel
            env: upperSnake
run:
    timeout: 2m
    skip-dirs:
        - doc
