name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'
env:
  GO_VERSION: 1.24.x
  GOLANGCILINT_VERSION: "1.64.8"

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v4
      name: Checkout
    - name: Build
      run: go build -v ./...
    - name: Run Tests
      run: |
        go test -v -race -covermode atomic -coverprofile=covprofile ./...

  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v4
        name: Checkout
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v${{ env.GOLANGCILINT_VERSION }}
          args: --verbose --max-same-issues=0 --max-issues-per-linter=0
