name: CI

env:
  GOLANGCILINT_VERSION: "1.55.2"
  GO_VERSION: 1.21.x

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.GOLANGCILINT_VERSION }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x

    - name: Run Tests
      run: |
        go test ./...
