name: ci

env:
  GO_VERSION: 1.21.x

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - uses: actions/checkout@v4
      name: Checkout
    - name: Build
      run: go build -v ./...
    - name: Run Tests
      run: |
        go test ./...
