name: lint
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  GOLANGCILINT_VERSION: "1.55.2"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v${{ env.GOLANGCILINT_VERSION }}
          args: --verbose --max-same-issues=0 --max-issues-per-linter=0
